
# Contributor & Editor: Style Guide

\#CS4RL

From LIBER Europe and the [LIBER Citizen Science Working
Group](https://libereurope.eu/working-group/liber-citizen-science-working-group/).

A guide book of around one hundred pages to be released incrementally in sections before the end of 2021.

*Working document - v1.2 [GitHub](https://github.com/CitSci-WG/guide),
14 June 2021* | [Issue tracker](https://github.com/CitSci-WG/guide/issues)

> Add comments using the [Hypothes.is](https://hypothes.is/) menu to the top right.

## Contact

The Editors-in-Chief: Simon Worthington (simon.worthington@tib.eu) and Thomas Kaarsted (thk@bib.sdu.dk).




## Mission statement

The guide is designed to be a practical and compact gateway publication for the
purpose of assisting research libraries to start setting up a Citizen Science
programme.

Citizen Science for research libraries is a way to build new and more engaged
audiences as a way to establish new links between science and society.

The guide will address the unique context of research libraries – as becoming
the ‘go to place’ for the new and exciting Open Science data world that is
opening up to the wider public.

As a starting point the guide will use the four recommendations for Citizen Science
from the [LIBER Open Science Roadmap](https://doi.org/10.5281/zenodo.1303002):
infrastructures; good scientific practice; guidelines, and; skilling.

## Contents

The content will be organised around the following four main sections and release in sequential modules for reuse. The top level sections are set but the section contents should be seen as working ideas or suggestions for content.

1.  **Skills:** Citizen Science skills development for staff, researchers, and the public;

2.  **Infrastructures:** As being active in the development of infrastructure for researchers to carry out Citizen Science;

3.  **Good [open] scientific practice:** as managing bodies around knowledge libraries that can translate good [Open Science] scholarly practice into new Citizen Science fields, and;

4.  **Guidelines:** develop guidelines for Citizen Science activities involving the library.

### Glossary

Start with Simple Knowledge Organization System ([SKOS](https://www.w3.org/2004/02/skos/)) terms, then fit to taxonomies, add to Wikidata, then describe. Use as a SEO primer. Here is an [Open Science](https://demo.hedgedoc.org/Dk4aKir9RyO1pi3jwr4Psw#Outline) example.

## Roadmap

First section will be released Sept 2021, with the publication released as a first full version by the end of 2023.

## Editorial management

- peer review / roles

**Co-Editors-in-Chief:** Simon Worthington and Thomas Kaarsted, reports to CSWG.
The role is that of content planning and project management – that contributions
fulfill the mission to make a compelling and exciting end product; ensuring
publication review groups and production workflows stay on track. **Duties:**
maintain content outline; organise meeting schedule; oversee technical
production, and; responsible for legal, ethical, and quality guidelines and
standards compliance on behalf of CSWG.

**Editorial committee (can also peer review):** Chair – Paul Ayris, with a
minimum of four members of the committee. The committee is made up of the
section editors. There will be one section editor per section of four sections
(optionally sometimes two section editors). The committee has the final
editorial signoff on content. The role of the committee is content coordination
and commissioning contributions – that sections have enough content, the right
type of content, and that style guides and templates, etc., are being followed.

**Section editors:** The role of the section editor is to oversee that the
content fits the scope and editorial policy. Section editors work with close
support from the Editors-in-Chief and report to the editorial committee with the
content of the section, recruit contributors, and correspond with peer
reviewers. Section editors would ensure that contributors have followed
contributor guidelines.

Section editors are:

1.  Citizen Science research infrastructure – Kirsty Wallis, University College
    London

2.  Good (Open Science) scholarly practice in Citizen Science – Bastian Greshake
    Tzovaras, OpenHumans

3.  Guidelines for Citizen Science programme development in libraries – Paul
    Ayris, University College London

4.  Citizen Science Skilling for Staff, Researchers, and the Public – Jitka Stilund Hansen, DTU Library, Technical University of Denmark, ORCID iD: [0000-0002-5888-1221](https://orcid.org/0000-0002-5888-1221) e-mail: jstha@dtu.dk

**Contributor:** A contributor would provide one or two articles in agreement
with section editors following the templates and style sheet of the guide.

**Peer review:** Carry out some parts as Open Peer Review. Made up of people
appointed by section editors. There will be two peer reviewers per section. The
reviews will be selected from – CSWG; editorial committee; external appointees,
and publication partners and collaborators.

**Scientific peer review:** The editorial committee would aim to appoint two
experts in the field as external reviewers.

**Partners:** Bring on contributing partners to the publication as institutional
partners. Primarily these partners would provide and exchange content, as
experts in the field, and be co-producers. These partners could also contribute
resources and be attributed: DOIs, ISBN, profiling, translations, etc. Letters
of agreement would be made with partners.

**Collaborations:** These would orientate around content provision, advocacy,
research and resource provision.

## Notes for editors

- Style guide, and contribution templates

Co-Editors-in-Chief Simon Worthington and Thomas Kaarsted will provide writers
guidelines for you to distribute to contributors.

All character counts are inclusive white spaces.

We would encourage contributors to do the following:

-   To make available check lists or materials used in CS activities and supply
    us with information on these and then we can see how to include them as
    either incorporated check lists or as external linked content.

-   To provide us with visual material to support contributions: photo
    documentation of past events; PDFs of promotional material, videos and video
    links so that we can look at how to creatively include these in articles.

-   References will be typeset as CMOS note bibliography per article, with no author date inline, and in a [Zotero Groups -
    Collection](https://www.zotero.org/groups/2420395/cswg/collections/HAJYX37C).

-   If possible use Zotero citation manager in Google Docs and store citations
    in the CSWG Zotero group, see:
    <https://www.zotero.org/groups/2420395/cswg/collections/HAJYX37C>

-   Sections should be thought of as 25 page sections, with 400 words a page as
    a guide.

### Style Guide

1.  Prepare the text in English. The Chicago Manual of Style 17th Edition (CMOS) is
    being used as the overall publication style. We will stay close to (CMOS) but not 100% complaint as we have many non/English native writers and stzles vary. Points to note will be:
    1. We will use an International English as the primary audience is English as a second language in Europe as the expectation of the reader leans towards UK English. For example end wods is ise and ize, but use US License as Creative Commons use the US form of license. This also applies to en and em dashes, use spaces unlike the US with no space. Refer to The Ecnoomist style guide as that caters to a US EN audience.
    3. Use the [Oxford Comma](https://cmosshoptalk.com/2020/02/11/oxford-chicago-and-the-serial-comma/). Which means the presence of a comma before and or or in a list of three or more items.  
    4. En and em dash policy. For em dash use we'll keep with CMOS guidlines on em dash used for puntuation em dash with space before and after (USA and CMOS have no space but in Europe it is more common to have space either side. Make sure en dashes are used where needed and not hyphens.

1. Typesetting punctuation:
    1. Use no breaking hyphens in phrases like Co&#8209;creation &ndash; Word instructions https://word.tips.net/T001116_Inserting_a_Non-Breaking_Hyphen.html &ndash; HTML https://www.toptal.com/designers/htmlarrows/punctuation/non-breaking-hyphen/

1. Capitalisation:
   1. For terms like open science, open access, open data, or FAIR data, etc. Generally we will aim for lowercase words to keep the reading flow easy, follow this rule for movements, schools. https://7sage.com/admissions/lesson/capitalization/ Capitalize the names of movements and schools derived from proper nouns; lowercase those that are not. Unfortunately, there are some exceptions: “Cynic,” “Scholasticism” and “New Criticism,” for example, are capitalized when used as movements. Look a term up in Merriam-Webster if you're not sure. romanticism; Keynesian economics; cubism; Cynicism. The rule of thumb can also be applied that capitalisation is to get rid of ambiguity. So in our example
     2. FAIR data would have acronym capitalised  
     3. Open science, open data, and open access &ndash; would all be lowercase
     4. Open source software &ndash; here we run into the 'rival camps' problem. There is the Free Software Foundation (Richard Stallman) and the Open Source (Eric Raymond) movement who disagree on ideologies. Properly the full term should be use Free and Open Source Software (FOSS) but its a mouthful. And there is more to the story. Our get out is to use the precompound adjective open-source.
     5. I will list more examples as they come up.
   1. Article titles capitalised as 'title capitalisation', running headers only first word and after :
   2. Job or role title removed.

## Using Fidus Writers

  - Guide: https://mrchristian.github.io/guide-en/

1. Note: Fidus Writer is designed as a semantic editors, for document editing and layout this means that there are some restrictions on editing like not being able to select fonts - instead style in terms of fonts, citation styles, etc., are applied on output. See the Book area of the site to preview content in final outputs such as PDF, eBook, Web, WebBook, etc.

1. Images: Images can be configured to appear in text as: figures, photos, to replace tables, etc. Also figures can be set to display captions or not. Last images can be set as 100%, 75%, 50%, and 25% width. Image widths can be set later at the time of publishing.

1.  Intro, author, and DOI styling. See example: https://write.handbuch.io/document/465. Intro uses the Abstract style. Author text as Normal style. DOI line is made as bold.

1. Adding or converting manual added citations. Fidus Writer has a citation manager that needs to be used as this applies citation style langauge to citations - styling them and organising them. Place cursor inline where you want the citation to be inserted. In top menu select Cite - you will be able to either search databases for citation or manually add a citation. The citation will be added inline and at bottom of article. Citations get automatically styled if citation style is changed. Citations can be edited by clicking them in the bottom of the article.

1. Inserting footnotes. Use * tool from format toolbar at top of document.

1. Tables. Tables can be added and edited from the format toolbar and via the three dot edit icon inline. Note: Currently in the CS Guide publications tables are exclusively used to style the info boxes. See information in the Article finishing section.

1. Spelling and grammar check: A spellchecker is available from the Tools menu. Once spelling and grammar checker has been loaded - right click on marked items to see correction suggestions. To remove marks use the menu item: Tools > Spelling and Grammar > Remove items.

1. Links: URL links can be added and edited. Do not use the internal links function as this does not work for all outputs.

1. Save revisions: You can make snapshot saved revisions - for example to save a copy prior to editing reviews. These revisions need to be loaded back into the system as new documents which is a bit cumbersome. Contact support to revert to a revision.

1. Sharing articles: to give others access to documents you need to share the document with a specific user. See the file menu for sharing options.

1. Track changes: There is full track changes functionality if needed. See the top level menu item in documents.

## Article finishing

1. Processing review edits: Save a names revision before processing edits so that we have a copy of the reviews if they have been added as comments or track changes.

1. Article images. Editors need to add article images. Articles need a featured image if possible, note its optional to have a featured image. This should be placed immediately after the article title or after the into and author credit. It depends on how the article looks in layout as to its placement. Place other images in the article to help communicate the work. If you cannot source any images then please raise a ticket and the editorial group will take on board the task.

1. Use of academic titles for authors and editors? Generally remove. But if unsure consult the editorial group for support https://github.com/cs4rl/guide/issues/35  
   1. Use them if provided by author in attribution? TBC
   1. Book information: Copyright pages, authors, etc., do not use

1.  The text should have a Title (between 1 and 10 words).

1.  The text should have a headline summary that briefly outlines the content of
    the section (max. 30 words).

1.  For each introduction author submit a name, department and institution, and ORCID iD. But not job title. See example https://write.handbuch.io/document/465

1. Article DOI line. Add as Article DOI: 10.25815/f360-s580 | You can retrieve DOIs from the article page plan Google spreadsheet. https://docs.google.com/spreadsheets/d/1cPhzMjs3otETY_jHPOa43TWs4IaGgIllmHa1SpcGsVY/edit#gid=0

1. Article **Info Boxes and Case Studies** formatting: Currently this is a bit of a work around as applying an inline style is not possible in other ways. To make an info box first create a table with only one cell, then paste content into the cell and format as usual. The effect of using the table is that it puts a blue background behind and around the text.

1.  Please divide the text into sections, with the following. Note: There is a Header hierarchy view on the left of Documents accessible via the 'scroll' icon.:

    1.  **Headings H2,**

    1.  *Subheadings H3.*

1.  Do not include a Table of Contents.

1.  Use single space for spacing.

1.  Do not use line spaces between paragraphs or for line spacing, instead use
    space before and after paragraph or header.

1. Use single column format.

1. Tables and figures. To be placed in individual files. Tables should serve a
    purpose and display cores data in a brief and structured way.

1. Each Table and Figure are automatically numbered by the publishing pipeline, there is no need to manually add them. A brief description placed
    below that correspond with the file. All Figures in min. 600 dpi resolution
    or vector graphic.

1. A maximum of three core references listed at the very bottom.

1. Use The Chicago Manual of Style 17th Edition style for references. All
    references should have an author or organization given first. Also please
    list a DOI for each reference if possible.

    Sample reference:

    Ayris, Paul, Isabel Bernal, Valentino Cavalli, Bertil Dorch, Jeannette Frey,
    Martin Hallik, Kristiina Hormia-Poutanen, et al. ‘LIBER Open Science
    Roadmap’. LIBER, 2 July 2018.
    [](https://doi.org/10.5281/zenodo.1303002https://doi.org/10.5281/zenodo.1303002).

1. For any additional details please contact the Co-Editors-in-Chief: Simon
    Worthington (<simon.worthington@tib.eu>) or Thomas Kaarsted
    (<thk@bib.sdu.dk>).

1. Author and editor profiles. ORCID ORCID iD: followed by 16 digit number and not URL as commonly used. No full stop or comma after ORCID iD or e-mail as to not interfere with both. Link to both and make links active.

See example: By Jitka Stilund Hansen, DTU Library, Technical University of Denmark, (ORCID iD: [0000-0002-5888-1221](https://orcid.org/0000-0002-5888-1221)).    

1. Refer to sections numbers as Section #1 or Section #2.

### Template Guides

#### Section introduction - to be written by section editor

-   The text is a maximum of 400 words, 2800 characters including spaces
    (including Tables, Figures, Photos)

    Title and headline.

-   One image

-   Add three or more learning outputs in an info box style. What you will learn
    in this section. An additional 300 words can be give to the 'learning outputs#.

Total for section into 700 words.

#### Quick start guide - [p5 example from SciStarter guide](http://media.scistarter.org/curated/The+Library+and+Community+Guide+to+Citizen+Science.pdf)

This could be to introduce a topic, or a service someone could use, like
FloraIncognita.

-   Main title, subtitle

-   Definition box: 6 bullet points

-   Video online tutorial: Title; image; description 255 characters; URL

-   Learn more: List of supporting resources - 1060 characters, 135 words

#### Overview / Essay / Expository text - p6 SciStarter (3 page example, can also be longer with 4 page example and more text 9000 characters)

##### 3 page version

-   Total character length 5600 characters, 830 words

-   Title, subtitle

-   Two images in main text

-   Main text: Use bullet points and sub-headers; 5000 characters of total

-   Summarise main points in infobox. No more than four points. 600 characters
    of total

-   End section to show how library can make use of idea, with examples for
    resources. Title; 1000 characters of total.

##### 4 page version

-   Total character length 9000 characters, 1320 words

-   Title, subtitle

-   Main text: Use bullet points and sub-headers; 7800 characters of total

-   Use a series of small images - 7 max. If images described in the text then
    no picture caption needed.

-   Use two info boxes to highlight important issues with bullet points and use
    an image here if preferred. 600 characters each of total char. length.

#### Project highlight or example, this could also count for a video piece - one pager p20 SciStarter

-   Title

-   Headline description 90 - 140 char.

-   One or two images

-   Text: 1200 -1500 characters

#### Step-by-step guide

##### Short - p28 SciStarter

-   Title, headline 95 characters

-   5000 characters; Use bullet points and sub-headers

-   2-4 images

##### Long - p30 SciStarter

-   Title, headline 95 characters

-   14,000 characters total

-   10 pictures max

-   Break process into no more than 7 steps of 500 characters each

-   Then following text

## Production

The book is intended as a short guide and will be approximately one hundred
pages in length. The publication will be produced in conventional and sprint/dash book sprints, as multi-format and
multi-channel distribution (print-on-demand, PDF, Webbook W3C+, website, eBook, and as a Jupyter
Book – and will be technically designed for reuse, for example in – community
translations or in MOOCs. High quality open standards, metadata, and modern sematic/computational publishing are a priority and research interest of the production process.

Book sections will be released incrementally as they are ready. Ideally the book
will become a community owned publication with regular updates.

### Design guide

 - Colour palette - https://coolors.co/user/palettes/640dd5ff7ed05b000cd8aa95

/* CSV */
00517b,eeb11e,215e9e,669ad2,000000

/* With # */
#00517b, #eeb11e, #215e9e, #669ad2, #000000

/* Array */
["00517b","eeb11e","215e9e","669ad2","000000"]

/* Object */
{"Indigo dye":"00517b","Xanthous":"eeb11e","Lapis Lazuli":"215e9e","Blue Gray":"669ad2","Black":"000000"}

/* Extended Array */
[{"name":"Indigo dye","hex":"00517b","rgb":[0,81,123],"cmyk":[100,34,0,52],"hsb":[200,100,48],"hsl":[200,100,24],"lab":[33,-4,-30]},{"name":"Xanthous","hex":"eeb11e","rgb":[238,177,30],"cmyk":[0,26,87,7],"hsb":[42,87,93],"hsl":[42,86,53],"lab":[76,11,74]},{"name":"Lapis Lazuli","hex":"215e9e","rgb":[33,94,158],"cmyk":[79,41,0,38],"hsb":[211,79,62],"hsl":[211,65,37],"lab":[39,4,-40]},{"name":"Blue Gray","hex":"669ad2","rgb":[102,154,210],"cmyk":[51,27,0,18],"hsb":[211,51,82],"hsl":[211,55,61],"lab":[62,-2,-34]},{"name":"Black","hex":"000000","rgb":[0,0,0],"cmyk":[0,0,0,100],"hsb":[0,0,0],"hsl":[0,0,0],"lab":[0,0,0]}]

/* XML */
<palette>
  <color name="Indigo dye" hex="00517b" r="0" g="81" b="123" />
  <color name="Xanthous" hex="eeb11e" r="238" g="177" b="30" />
  <color name="Lapis Lazuli" hex="215e9e" r="33" g="94" b="158" />
  <color name="Blue Gray" hex="669ad2" r="102" g="154" b="210" />
  <color name="Black" hex="000000" r="0" g="0" b="0" />
</palette>

 - Fonts

Crimson text - Headers, https://fonts.google.com/specimen/Crimson+Text?query=Crimson+text

Lato - Body,  https://fonts.google.com/specimen/Lato?query=Lato

## Acknowledgements

We would like to acknowledge [The Library & Community Guide to Citizen
Science](http://media.scistarter.org/curated/The+Library+and+Community+Guide+to+Citizen+Science.pdf)
published by [SciStarter](https://scistarter.org/) as an inspiration for the
idea for our publication. Additionally [The Turing
Way](https://the-turing-way.netlify.app/welcome) from the Alan Turing Institute
is worth mentioning as a community model of open science publishing that we look
to emulate.

## An Open Science publication

The publication will be produced as an Open Access publication and use Open
Science practices – where appropriate – to ensure the research is open and
reusable as possible, including: open data, open standards, PIDs, open peer
review, open source software, and open methods, etc.

© 2021 the authors. All content licensed Creative Commons:
Attribution-ShareAlike 4.0 International (CC BY-SA 4.0), unless otherwise
stated. <https://creativecommons.org/licenses/by-sa/4.0/> \| Publication:
<https://github.com/CitSci-WG/guide>

## References

Ayris, Paul, Bernal, Isabel, Cavalli, Valentino, Dorch, Bertil, Frey, Jeannette,
Hallik, Martin, Hormia-Poutanen, Kristiina, et al. “LIBER Open Science Roadmap”.
Zenodo, July 2, 2018. doi: <https://doi.org/10.5281/zenodo.1303002>. Page 29.

Mahey, Al-Abdulla, Ames, Bray, Candela, Chambers, Derven, et al. Open a Glam Lab. Doha, Qatar: Digital Cultural Heritage Innovation Labs, 2019. https://glamlabs.io/books/open-a-glam-lab/.

Cavalier, Darlene, Caroline Nickerson, Robin Salthouse, and Dan Stanton, eds.
The Library & Community Guide to Citizen Science. SciStarter, 2020 (Revised
2021). <http://media.scistarter.org/curated/The+Library+and+Community+Guide+to+Citizen+Science.pdf>.

Arnold, Becky, Louise Bowler, Sarah Gibson, Patricia Herterich, Rosie Higman,
Anna Krystalli, Alexander Morley, Martin O’Reilly, Kirstie Whitaker, and The
Turing Way Community. The Turing Way: A Handbook for Reproducible Data Science, 2019. <https://doi.org/10.5281/zenodo.3233986>.  

---

**Footer**

© 2021-23 the authors. All content licensed Creative Commons:
Attribution-ShareAlike 4.0 International (CC BY-SA 4.0), unless otherwise
stated. <https://creativecommons.org/licenses/by-sa/4.0/> \| Publication:
<https://github.com/CitSci-WG/guide>.

Imprint: Responsible for the content of the domain https://github.com/CitSci-WG/guide/ - Simon Worthington (LIBER CSWG Secretary), Lausitzer Platz 10, 10997 Berlin, Germany. E-mail: simon.worthington AT tib.eu - Internet: [https://libereurope.eu/working-group/liber-citizen-science-working-group/](https://libereurope.eu/working-group/liber-citizen-science-working-group/). The respective authors are responsible for the content of their posts.

Data protection: No data trackers are used on this site and no personal information is stored. Data protection notice - version 1.1, 16 July 2023.
